### ISSUE TITLE
[Bug]: infinite load screen

### ISSUE THREAD

**Issue by binded-zz** [tupoy-ya/TupoyeMenu#50]
### Describe the bug

infinite load screen
lose connection to internet
none full load of lobby
kicked from a session try to join a new one stuck on hud swoop down windows
no way out but to hard close game 
sometimes able to click fast join on and off gets by loading screen not all the time 

seems to only been tupoye menu

i like this one over the stock i like the menu layouts and the Jesus's

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

None

### Additional context

as far as i can tell stock YM does not do this 

### Build

- [X] I've confirmed the issue exists on the latest version of TupoyeMenu and does not exist on the latest version of YimMenu

**Comment by tupoy-ya** [comment]
Should be fixed in 6c31e00df8a6afc13941bd7f60741b134fd584b3, but i didn't test it much.

**Comment by binded-zz** [comment]
thank you your awsome i 
seemed to be fixxed i had buttons to continue and what not when i tested it the other day

**Comment by binded-zz** [comment]
i still get the loading screen 
connection to the session host has been lost. unable to determine a new host. the GTA online session will be terminated.
joining a new gta online session.

wait hud exit | 5 even with the continue button its stuck
